### ISSUE TITLE
Technical query re application https://pypreservica.pythonanywhere.com/

### ISSUE THREAD

**Issue by MICHAELHUNKIN** [carj/flask-csv2xml#1]
Hi James,

Just had a quick query about CSV/metadata convertor link you posted on Preservica User Group last week - the post mentioned to send any queries via the GitHub pages.

https://pypreservica.pythonanywhere.com/

I've set my spreadsheet to display the DC elements (i.e. title, creator) in columns, with each file running left to right, with what will be the files running in rows below the column heading. I put the spreadsheet through the application to convert it to DC .metadata files, but the files are coming out with all the elements placed together in one line, rather than in indented rows below the namespace The PUT tool will not allow me to move an ingest package into the system whilst the metadata files are in this format. If I move the elements into lines as per my metadata templates in Preservica it's fine, but its a bit time consuming to amend all the files this way. 

Is the application supposed to order the elements in rows automatically, I'm assuming it does so think it's something I'm doing wrong. Sorry to bother you with this, I have very limited experience of coding and using XML schemas in the context of Preservica, and have not really got to grips with the API side of things either. Not sure if it's something I'm doing wrong with the web application or how I'm creating my CSV document. I have saved the spreadsheet as CSV in UTF-8.

Any guidance would be gratefully received!

Best wishes,

Mike

**Comment by carj** [comment]
Hi Mike
I updated the web app to format/indent the created XML documents in a nice human readable way. This should make it easier to check the resulting XML files are correct even though Preservica does not need the XML files to be formatted nicely.

**Comment by MICHAELHUNKIN** [comment]
Hi James,

Thanks for updating the web app, is a lot easier to check with the structured text option and spot mistakes.

I've played around with it a bit more and managed to get something ingested! I had to bring a modified schema that corresponded to the metadata files (also created in the web app) and activate it in the system, this seemed to make it work.

So, my metadata files have the long top line including just the xmlns:oai_dc and xmlns:dc bits. The DC XML templates already in the system (oai_dc:dc) have the extended line:

-<oai_dc:dc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ oai_dc.xsd">

I'll keep playing around with it, see how it copes with bigger ingests. I'll also get in contact with a few colleagues in other places to see how they get bulk metadata together. We're still looking at CALM integration but would look at Dublin Core for uncatalogued material or digital content that we'd not normally document on the CALM system. For getting files together quickly this a very useful tool though, now I'm up to speed with it - thanks for putting it together and for your help with my questions!

Best wishes,

Michael

________________________________
