### ISSUE TITLE
New CSV spreadsheet converter - can't upload file

### ISSUE THREAD

**Issue by nikkibo77** [carj/flask-csv2xml#2]
I am trying to use the new version of the CSV spreadsheet converter, but when I attempt to upload a CSV file via the "Choose File" button, nothing happens, it doesn't bring me to my files to select one for upload. I tried reloading the page, but not sure how else to troubleshoot this. Thanks.

**Comment by nikkibo77** [comment]
Looks like it works in Safari browser...I was using Chrome. Problem solved.

**Comment by carj** [comment]
Hi
I have just tried it using chrome on my windows machine (Version 109.0.5414.75 ) and it allowed me to select a csv ok.

I don't have a mac to test it on, just a windows machine.
